import type { Metadata } from "next";
// import { Montserrat, Press_Start_2P, Tourney } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import localFont from 'next/font/local';

const pressStart2p = localFont({
  src: '../../public/fonts/PressStart2P-Regular.ttf',
  variable: "--font-press-start-2p",
  weight: "400"
})


// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
//   weight: "800"
// });

// const pressStart2p = Press_Start_2P({
//   variable: "--font-press-start-2p",
//   subsets: ["latin"],
//   weight: "400"
// });

// const tourney = Tourney({
//   variable: "--font-toruney",
//   subsets: ["latin"],
//   weight: "400"
// });



export const metadata: Metadata = {
  title: "Poznaj Merito",
  // description: "Generated by create next app",
};

// ${montserrat.variable}
// ${tourney.variable}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        style={{backgroundColor: "black"}}
        className={`
          min-h-screen
          ${pressStart2p.variable}          
          antialiased`}
      >
        <div className={'monitor-margin'}>
          <div className={'monitor'}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
